# Generated by Django 4.0.6 on 2024-09-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='user',
            new_name='coffeeuser',
        ),
    ]
