# Generated by Django 4.0.6 on 2024-09-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='debth',
            field=models.IntegerField(default=0),
        ),
    ]
