# Generated by Django 4.0.6 on 2024-09-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_employee_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='lukas.lenz@eonerc.rwth-aachen.de', max_length=255),
            preserve_default=False,
        ),
    ]
