# Generated by Django 4.0.6 on 2024-09-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employee_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='employee',
            name='qr',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
