# Generated by Django 4.0.6 on 2024-09-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_employee_options_employee_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='coffees',
            field=models.IntegerField(default=0),
        ),
    ]
