# Generated by Django 4.0.6 on 2024-09-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_extendeduser_coffee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
