# Generated by Django 4.0.6 on 2024-09-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_coffee_options_alter_coffee_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
