# Generated by Django 4.0.6 on 2025-06-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_employee_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='building',
            field=models.CharField(choices=[('Main Building', 'Main Building'), ('Sense Building', 'Sense Building')], default='Main Building', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('Hiwi', 'Hiwi'), ('Research Assistant', 'Research Assistant')], default='Research Assistant', max_length=255),
        ),
    ]
