apiVersion: v1
kind: Service
metadata:
  name: acs-coffee
  namespace: acs-coffee-list
  labels:
    app: acs-coffee
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: acs-coffee
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  namespace: acs-coffee-list
spec:
  selector:
    matchLabels:
      app: acs-coffee # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: acs-coffee # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: acs-coffee
        image: uniquedockeraccount/django-coffee:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/acs-coffee
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi